### ISSUE TITLE
Multi Instance Configuration not Saved to Persistent Storage

### ISSUE THREAD

**Issue by SpeicherBox** [Intermesh/docker-groupoffice#11]
I have noticed, that the multi_instance configuration located under /etc/groupoffice/multi_instance is not saved to the persistent goetc volume. This will lead to data loss if the container is restarted or update. As we have multiple instances configured, we can't access the data anymore as the config.php for the corresponding instance is missing.

Hostversion: Ubuntu 20.04
Docker Version: 20.10.7-0ubuntu5~20.04.2
Group Office Version: latest (updated today)

docker-compose.yaml

```
version: "3.1"
services:
  groupoffice:
    image: intermesh/groupoffice:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
    volumes:
      - "godata:/var/lib/groupoffice:cached"
      - "goetc:/etc/groupoffice:cached"
      - "./etc/ssl/groupoffice:/etc/ssl/groupoffice"

    env_file:
      - ./db.env
  db:
    image: mariadb
    restart: always
    env_file:
      - ./db.env
    environment:
      MYSQL_ROOT_PASSWORD: groupoffice
    volumes:
      - "dbdata:/var/lib/mysql:cached"
volumes:
  godata:
  goetc:
  dbdata:
```

If i touch a file inside /etc/groupoffice it will be written to the persistent volume
```
root@652da5f8d058:/var/www/html# touch /etc/groupoffice/test.txt
```
Result form Local Filesystem
```
sudo ls -ll /var/lib/docker/volumes/docker-groupoffice_goetc/_data/
total 12
-rw-r--r-- 1 root     root      288 Nov 25 12:10 config.php
-rw-r--r-- 1 root     root      285 Jun 17 13:14 config.php.tpl
drwxr-xr-x 2 www-data www-data 4096 Jun 17 13:19 multi_instance
-rw-r--r-- 1 root     root        0 Nov 25 12:19 test.txt
```
If i touch a file inside etc/groupoffice/multi_instance it will not be written to the persistent volume
```
root@652da5f8d058:/var/www/html# touch /etc/groupoffice/multi_instance/test.txt
```
Result from local File system
```
sudo ls -ll /var/lib/docker/volumes/docker-groupoffice_goetc/_data/multi_instance/
total 0
```

What could be the issue, the those configuration are keept in the container? Is it possible to restore the old configurations to regain access to the instances?

Thank you very much for a fast reply.
