### ISSUE TITLE
How to tell Group Office to connect to existing DB container?

### ISSUE THREAD

**Issue by zine999** [Intermesh/docker-groupoffice#18]
If I already have a MariaDB container, how do I set up the docker-compose.yml and update what config files to get it working with that container?

The way the example Dockerfile is written seems to assume that the MariaDB container will only be used for Group Office:

```yml
  db:
    image: mariadb:11.1.2
    restart: always    
    env_file:
      - ./db.env
    environment:
      MYSQL_ROOT_PASSWORD: groupoffice
      MARIADB_AUTO_UPGRADE: 1
```

But I have an existing Mariadb instance that I'd like it to use and for it to use it with with its own user (not the "root" user).
