### ISSUE TITLE
Container resets config.php to default values on restart

### ISSUE THREAD

**Issue by dom6770** [Intermesh/docker-groupoffice#24]
Hello,

I'm going for my second attempt to migrate our bare-metal installation to a docker installation, but I'm having some issues.

Whenever I restart my docker container, my config.php configuration is lost and will be reset as soon as the container starts up again, and I'm looking at the installation screen again.

Here's my docker-compose.yaml:

```
services:
  groupoffice:
    image: intermesh/groupoffice:6.6

    ports:
      - "9090:80"

    volumes:
      - ./data:/var/lib/groupoffice:cached
      - ./etc:/etc/groupoffice:cached
      # - ./modules:/usr/local/share/groupoffice/go/modules/studio

    env_file:
      - ./.env

  mariadb:
    image: mariadb:11.1

    env_file:
      - ./.env

    environment:
      MYSQL_ROOT_PASSWORD: groupoffice
      MARIADB_AUTO_UPGRADE: 1
    
    ports:
      - "9091:3306"

    volumes:
      - ./mariadb:/var/lib/mysql:cached
```

The /etc directory has the config.php with 0644 and www-data as owner and group, and as soon as I startup the container it's getting replaced by the default configuration:

```
<?php
$config['db_name'] = "groupoffice";
$config['db_host'] = "db";
$config['db_user'] = "groupoffice";
$config['db_pass'] = "groupoffice";
$config['db_port'] = 3306;
$config['file_storage_path'] = "/var/lib/groupoffice";
$config['tmpdir'] = "/tmp/groupoffice";
$config['debug'] = false;
$config['business'] = array (
	'studio' =>
		array (
			'package' => 'studio',
		)
	);
```

Which should definitely not happen. We configure LDAP and SMPT through this config. 

My workaround right now is to mount it as read-only.
